version: '3.2'

services:

  main:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/letsencrypt/registry.imakethingsfortheinternet.com.crt
      - REGISTRY_HTTP_TLS_KEY=/etc/letsencrypt/registry.imakethingsfortheinternet.com.key
    volumes:
      - registry:/var/lib/registry
      - le-certs:/etc/letsencrypt
    networks:
      - registry
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.letsencrypt.host=${REGISTRY_DOMAIN:-localhost}
        - com.df.letsencrypt.email=pat@patscott.io
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 200M

volumes:

  registry:
    driver: cloudstor:aws
    external: false

  le-certs:
    driver: cloudstor:aws
    external: true

networks:

  registry:
    external: true