version: '3.2'

services:

  main:
    image: registry
    volumes:
      - registry:/var/lib/registry
    networks:
      - registry
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 200M

volumes:

  registry:
    driver: cloudstor:aws
    external: false

networks:

  registry:
    external: true